config/routes.rb
Rails.application.routes.draw do

  resources :search_suggestions

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
  get 'notifications', to: 'notifications#index'

  get '/posts/hashtag/:name', to:'posts#hashtags'

  resources :faqs do 
    resources :replies
  end 

  resources :posts do 
    resources :comments 
    collection do # new path for search input 
      get :search 
    end 
  end
  devise_for :users
  resources :users do
    member do
      get :friends
      get :followers
      get :mentionable
      get :deactivate
    end
  end

  authenticated :user do
    root to: 'home#index', as: 'home'
  end
  unauthenticated :user do
    root 'home#front'
  end

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post
  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :find_friends, to: 'home#find_friends', as: :find_friends, via: :get
  match :about, to: 'home#about', as: :about, via: :get
  match :search, to: 'home#search', as: :search, via: :get
  match :privacy, to: 'home#privacy', as: :privacy, via: :get
  match :Terms, to: 'home#terms', as: :terms, via: :get

  resources :tlks do
    resources :mls
  end

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :notified_by, class_name: 'User'
  belongs_to :post

  validates :user_id, :notified_by_id, :post_id, :notice_type, presence: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def link_through
    @notification = Notification.find(params[:id])
    @notification.update read: true
    redirect_to post_path @notification.post
  end

  def index
    @notifications = current_user.notifications
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<li>
  <%= link_to "#{notification.notified_by.name} has #{notification.notice_type}ed on your post", link_through_path(notification)%>
</li>

app/views/notifications/_notification_dropdown.html.haml
.dropdown.notification-dropdown
  %button.btn.btn-primary.dropdown-toggle{ type: 'button', id: 'dropdownMenu1', data: { toggle: 'dropdown' }, 'aria-haspopup': true, 'aria-expanded': true }
    = current_user.notifications.count
    Notifications
  %ul.dropdown-menu{ 'aria-labelledby': 'dropdownMenu1' }
    %li.dropdown-header.text-center Notifications
    = render current_user.notifications.where(read: false)
    %li.divider{ role: 'separator' }
    %li.text-center= link_to 'View All', notifications_path

app/views/notifications/index.html.erb
      <ul class="notification-index-list">
        <%= render @notifications %>
      </ul>
    
