config/routes.rb
Rails.application.routes.draw do

  resources :search_suggestions

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
  get 'notifications', to: 'notifications#index'

  get '/posts/hashtag/:name', to:'posts#hashtags'

  resources :faqs do 
    resources :replies
  end 

  resources :posts do 
    resources :comments 
    collection do # new path for search input 
      get :search 
    end 
  end
  devise_for :users
  resources :users do
    member do
      get :friends
      get :followers
      get :mentionable
      get :deactivate
    end
  end

  authenticated :user do
    root to: 'home#index', as: 'home'
  end
  unauthenticated :user do
    root 'home#front'
  end

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post
  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :find_friends, to: 'home#find_friends', as: :find_friends, via: :get
  match :about, to: 'home#about', as: :about, via: :get
  match :search, to: 'home#search', as: :search, via: :get
  match :privacy, to: 'home#privacy', as: :privacy, via: :get
  match :Terms, to: 'home#terms', as: :terms, via: :get

  resources :tlks do
    resources :mls
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :set_user, except: :front
    respond_to :html, :js
  
    def index
      
      @post = Post.new
      @friends = @user.all_following.unshift(@user)
      @activities = PublicActivity::Activity.where(owner_id: @friends).order(created_at: :desc).paginate(page: params[:page], per_page: 100)
    end
  
    def front
    end
  
    def find_friends
      @friends = @user.all_following
      @users =  User.where.not(id: @friends.unshift(@user)).paginate(page: params[:page])
    end
  
    private
    def set_user
      @user = current_user
    end
end

app/helpers/home_helper.rb
module HomeHelper
    def relative_time(created_at)
      time_ago_in_words(created_at)
    end
  
    def formatted_time(time)
      time.to_formatted_s(:short)
    end

    def resource_name
      :user
    end
  
    def resource
          @resource ||= User.new
    end
 
end

app/views/home/about.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3 well">
    <h3 class="text-center">ABOUT</h3>
    <hr>
    <h3>What?</h3>
    <p>
      Socify is a social networking app built using Ruby on Rails. It's free &amp; completely open source. You can check the source on <a href="https://github.com/sudharti/socify"><%= fa_icon 'github' %> Github</a>. Also take a look at the demo deployed to <a href="http://socifyapp.herokuapp.com/">Heroku</a>.
    </p>
    <br>
    <h3>Why?</h3>
    <p>
      I am not building the next Facebook. Given that there are enough social networks already I don't want to end up launching one. Pointless! So why am I building? I want to try and learn how to develop a social network and in the process show you how easy it is done using Rails. Here is the <a href="https://medium.com/@sudharshanmuralidharaniyer/eb31da569233"><%= fa_icon 'medium' %> Blog post</a>.
    </p>
    <br>
    <h3>How?</h3>
    <p>
      As stated above it's a Ruby on Rails application. Frontend is developed using Twitter Bootstrap. Database is SQLite for development and Postgresql for production.
    </p>
    <br>
    <a href="https://github.com/sudharti/socify" class="btn btn-warning">
      <%= fa_icon 'star' %> Star it
    </a>
    <a href="https://github.com/sudharti/socify" class="btn btn-primary">
      <%= fa_icon 'code-fork' %> Fork it
    </a>
  </div>
</div>

app/views/home/faq.html.erb
<p id="notice"><%= notice %></p>


<h1>Frequently Asked Questions</h1>

<h1><%= link_to 'Ask A Question', new_faq_path %></h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @faqs.each do |faq| %>
      <tr>
        <td><%= faq.description %></td>
        <td><%= link_to 'Show', faq %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>


                          
<br>



app/views/home/find_friends.html.erb
<div class="row">
  <div class="col-lg-4">
    <%= render 'shared/user_info' %>
  </div>
  <div class="col-lg-5 well">
    <h3>Find Friends</h3>
    <hr>
    <div id="users">
      <%= render(@users) || render('shared/no_resource', resources: 'Users') %> 
    </div>
    <%= render 'shared/paginate', resources: @users %>
  </div>
  <div class="col-lg-3">
    <%= render 'shared/links' %>
  </div>
</div>

app/views/home/find_friends.js.erb
$('#users').append("<%= j render(@users) %>");

<%= render 'shared/paginate', resources: @users %>

app/views/home/front.html.erb
    <style>
        body {
            background: linear-gradient( /* somewhat transparent film on top of the BG to make it look darker. */
                rgba(0,0,0, 0.4),
                rgba(0,0,0, 0)
                ), url("/star.jpg") no-repeat center center fixed
            
            
        }
        h3 {
            color: purple;
            font-weight: bold;
        }

        
        
        h5 {
          color: black;
            
        }
        h6 {
          color: blue;
            
        }
        td{
          color: white;
            
        }
      
     
    </style>
    
  <div class="row">     
            <div class="col-lg-3">
                <%= render "devise/sessions/form" %> <br>               
                  <%= render "devise/registrations/form" %>
  </div>
  <div class="col-lg-8 col-lg-offset-0 well"> 
              <center>
                <h3> About Flick </h3>
              </center>
              <div class="col-lg-8 col-lg-offset-1">
                    <h5>Flick is a social media directory where people can unleash their creativity </h5>
              </div>
              <div class="col-lg-8 col-lg-offset-2">
                    <h5> and connects with like minded people that shares the same</h5> 
              </div>
              <div class="col-lg-8 col-lg-offset-3">
                <h5> goals, interests and passions</h5>
              </div>
              
                 <br> <br><br><br><br><br><br><br>

                  <center><p style="background-color:purple;color:white;font-weight: bold;">
                     Founder & CEO: Brima Manso Bangura
                  </p></center>


                  <div class="col-lg-8 col-lg-offset-3">
                    a Brima Manso Bangura production
                  </div>
                  <div class="col-lg-8 col-lg-offset-4">
                    flick (c) 2018
                  </div>


      
                    
  </div>
    









app/views/home/index.html.erb
<div class="row">
  <div class="col-lg-4">
    <%= render 'shared/user_info' %>
  </div>
  <div id="newsfeed" class="col-lg-6">
    <%= render 'posts/form' %>
    <div class=" post-panel">
        <div id="activities">
          <% if @activities.empty? %>
            <div class="well">
              <%= render('shared/no_resource', resources: 'Activities') %>
            </div>
          <% else %>
            <%= render_activities(@activities, layout: '/shared/activity') %>
          <% end %>
        </div>
    </div>
    <div class="panel panel-default pic-panel">
        <div class="panel-body row">
          <div class="col-lg-6">
            <a href="#top"><p class="opacity: .7;">Back to top <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span></p></a></center>
          </div>
        </div>
    </div>
    <%= render 'shared/paginate', resources: @activities %>
  </div>
</div>

app/views/home/index.js.erb
$('#activities').append("<%= j render_activities(@activities, layout: '/shared/activity') %>");

<%= render 'shared/paginate', resources: @activities %>

app/views/home/privacy.html.erb
<style>
        h3 {
            color: purple;
            font-weight: bold;
        }  
        h4 {
            color: purple;
        } 
        h5 {
          color: purple;           
        }
        h6 {
          color: blue;            
        }
        td{
          color: white;           
        }
</style>


<div class="row">
    <div class="col-lg-6 col-lg-offset-3 well">
        <center>
                <h3> Flick Privacy Policy</h3>
                <hr>
        </center>

        <p>This website's Privacy Policy is designed to help you understand how we collect,
             use and safeguard the information you provide to us and to assist you in making informed decisions when using our website.</p>
        <p>For the purpose of this agreement, “Site” refers to the Company’s website, 
            “we,” “us,” and “our” refer to the Company. “You” refers to you, as a user of our Site. Please note that by accessing 
            our Site, you accept our Privacy Policy and our <%= link_to 'Terms&Condition', terms_path %> and you consent to our 
            collection, storage and use of your Personal Information as described in this Privacy Policy.
        </p>

        <hr>
        
        <center>
            <h4>I. INFORMATION WE COLLECT </h4> 
        </center>
        <p>
            In order to use this site, a user must first complete the registration form located at the 
            homepage of the website which includes some required personal information. These information includes your full name, 
            email address and a password which you submit to us through the registration process at the Site. Please note that you must 
            have an authentic email address since a confirmation email will be sent to you after registration which will confirm your email 
            that you registered with. Additionally, only authenticated users who successfully registered will have access to see contents 
            of the website. 
            <p>If you log out and wants to log in again, you will need to submit the email address 
                and the password that you registered with before. By registering, you are authorizing us to collect, 
                store and use your email address in accordance with this Privacy Policy. 
            </p>
            <p>After creating your account, authenticated users will need to edit their personal profile. 
                Please note that you are not required to add a profile picture, cover picture or any other personalized questionnaires 
                that you may find in the edit profile page. However, it is recommended that you do fill out some of the questions that 
                interests you and makes you the person that you are. 
            </p>
            <p>The website is not directed to anyone under the age of 13. The Site does not knowingly collect or 
                request information from anyone under the age of 13, or allow anyone under the age of 13 to register. In the event 
                that we learn that we have gathered personal information from anyone under the age of 13, we will delete that 
                information as soon as possible. If you believe we have collected such information, please contact 
                us at [Company contact email address]. 

                User Content (e.g., photos, comments, and other materials) that you post to the Service.
            </p>
        </p>
        </hr>

        <center>
            <hr>
                <h4>II. HOW WE USE AND SHARE INFORMATION  </h4>
        </center>
        <h5> Required Personal Information: </h5> 
        <p>Except as otherwise stated in this Privacy Policy, we do not sell, rent or share your Personal Information with any third parties.
            On the other hand, we may share your Personal Information with a third party if we have a good 
            reason to believe that the disclosure of your information is sensibly needed to meet any appropriate legal process or 
            enforceable governmental request; including investigation of potential violations; address fraud, security or technical 
            concerns; or to protect against harm to the rights, property, or safety of our users or the public as mandatory or permitted by law. 
        </p>
        <h5>Non-Personal Information </h5>
        <p>In general, we use Non-Personal Information to help us improve the Service and customize the user experience.
            We also combine Non-Personal Information in order to track trends and analyze use patterns on the Site. For this we use google 
            analysis that helps….This Privacy Policy does not limit in any way our use or disclosure of Non-Personal. If our information 
            practices change at any time in the future, we will post the policy changes to the site. We kindly suggest that you check 
            the Site periodically if you are concerned about how your information is used. 
        </p>
        <hr>
        <h4>HOW WE PROTECT INFORMATION </h4>
        <p> We implement security measures designed to protect your information from unauthorized access. 
            Your account is protected by your account password and we urge you to take steps to keep your personal information 
            safe by not disclosing your password and by logging out of your account after each use. We further protect your information 
            from potential security breaches by implementing certain technological security measures including encryption. However, these 
            measures do not guarantee that your information will not be accessed, disclosed, altered or destroyed by breach of such secure 
            server software. By using our Site, you acknowledge that you understand and agree to assume these risks.
            <p>This Privacy Policy applies solely to information collected by us through the Site. We are not responsible for the privacy 
                practices employed when a user posts a link to a website in our site. Therefore, this Privacy Policy does not apply to your 
                use of a third party website accessed by you posting a link on our Site. To the extent that you access another website or 
                application, then the privacy policy of that other website or application will apply to your access or use of that site or 
                application. We encourage our users to read the privacy statements of other websites before proceeding to use them. 
            </p>
        </p>
        <hr>
        <h4>CHANGES TO OUR PRIVACY POLICY </h4>
        <p>We reserves the right to change this policy and our Terms of Service at any time. 
            You should periodically check the Site and this privacy page for updates or significant changes
        </p>
        <hr>
        <h4>CONTACT US </h4>
          <p>  If you have any questions regarding this Privacy Policy or the practices of this Site, 
            please contact us by sending an email to [Insert Company Email]. </p>
            <h5>Last Updated: This Privacy Policy was last updated on March 2018 <h5>


    </div>
</div>

app/views/home/terms.html.erb
<h1>All requirements for the site here:: </h1>